Manual updates for 3.0
PolymerElements/iron-scroll-target-behavior pull request #45
Opened 2018-06-27 23:19 UTC by keanulee

2018-06-27 23:56 UTC, e111077 requested changes

2018-06-27 23:56 UTC, e111077 commented on demo/document.html
> +    <script src="https://unpkg.com/@webcomponents/webcomponentsjs@^2.0.0/webcomponents-bundle.js"></script>
Please change bundle to loader

2018-06-27 23:56 UTC, e111077 commented on demo/scrolling-region.html
> +    <script src="https://unpkg.com/@webcomponents/webcomponentsjs@^2.0.0/webcomponents-bundle.js"></script>
please change bundle to loader

2018-06-28 01:34 UTC, e111077 requested changes
missing travis changes

2018-06-28 22:24 UTC, e111077 approved these changes

2018-06-29 21:02 UTC, dfreedm reviewed
Travis changes LGTM

2018-07-10 22:28 UTC, merged